name = "HANK_MNS"
uuid = "bc72741d-12da-4c12-b738-4ce9ecb346c5"
authors = ["000martin <mrtn.bretschneider@gmail.com>", "mhaense1 <matthias.hansel@phdstudent.hhs.se>"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
